"""Weekly self-review — the system grades its own week and proposes fixes.

Reads three ledgers the pipeline already keeps:
  - content_log   (what was said + the operator's fb_* annotations)
  - sent_log      (what actually reached LINE, incl. failures)
  - calibration_log (what gold actually did after each event)

…and produces one private 1:1 card a week: volume, the feedback received,
and a short "สิ่งที่อยากให้แก้" list generated by explicit rules — the same
shape as the EoD recap, but weekly, introspective, and never for the group.

Pure functions, no I/O. `main.run_content_review` wires Store + LINE.

Design rule: every suggestion must cite the data that triggered it (counts,
example titles). No vibes — if no rule fires, the card says so instead of
inventing advice. The rules are deliberately transparent so a suggestion can
be traced back to sheet rows and, when White disagrees, refuted from them.
"""
from __future__ import annotations

import re
from collections import Counter
from datetime import datetime, timedelta
from typing import Any

from .utils_time import ICT, parse_iso

WEEK_DAYS = 7
# Same "the market actually cared" bar as precision_report: a 30-min move of
# at least this magnitude after a REJECTED event suggests the filter dropped
# something the tape responded to.
HIGH_MOVE_PCT = 0.15
MAX_SUGGESTIONS = 5

_DELIVERED = {"200", "200.0"}
_OK = {"y", "yes", "ok", "1", "true", "ดี"}
_BAD = {"n", "no", "x", "0", "false", "ไม่", "แก้"}


def parse_ts_ict(s: Any) -> datetime | None:
    """content_log.ts_ict is 'YYYY-MM-DD HH:MM:SS' in ICT (no offset)."""
    try:
        return datetime.strptime(str(s).strip(), "%Y-%m-%d %H:%M:%S").replace(tzinfo=ICT)
    except (ValueError, TypeError):
        return None


def _to_float(v: Any) -> float | None:
    try:
        f = float(v)
    except (TypeError, ValueError):
        return None
    if f != f or f in (float("inf"), float("-inf")):
        return None
    return f


def _fb_state(row: dict[str, Any]) -> str:
    """'ok' | 'issue' | '' (not reviewed). fb_type filled counts as a review
    even when fb_ok was left blank — the operator clearly looked at it."""
    v = str(row.get("fb_ok") or "").strip().lower()
    if v in _OK:
        return "ok"
    if v in _BAD:
        return "issue"
    if str(row.get("fb_type") or "").strip():
        return "issue"
    return ""


def _reject_reason(flags: str) -> str:
    """Pull `<reason>` out of 'rejected:<reason> …' (see main.py writers)."""
    for tok in str(flags or "").split():
        if tok.startswith("rejected:"):
            return tok.split(":", 1)[1] or "unknown"
    return "unknown"


# ---------------------------------------------------------------------------
# Automatic QC — deterministic checks over the week's SENT Thai copy, so the
# self-review finds content problems even in a week where the operator never
# opens the sheet. Zero cost (no LLM, no network): these are exactly the
# defects a human reviewer keeps catching by eye, encoded once.
# ---------------------------------------------------------------------------

# CJK scripts that must never appear in Thai output (the translate-time
# validator forces a fallback on leaks, but the fallback path itself and the
# Gemini tier have leaked before — this is the after-the-fact audit).
_CJK_RE = re.compile(r"[一-鿿぀-ヿ가-힯]")

# Names the translator glossary maps to canonical Thai. Seeing the raw EN form
# in shipped Thai copy means the glossary was bypassed (fallback path) or the
# model ignored it. Word-boundary match, case-sensitive on the capitalised form.
_GLOSSARY_NAMES = (
    "Powell", "Trump", "Putin", "Zelensky", "Netanyahu", "Lagarde",
    "Yellen", "Biden", "Xi Jinping", "Ueda", "Bailey",
)

_QC_LABELS_TH = {
    "untranslated": "หัวข่าวยังเป็นอังกฤษ (ไม่ถูกแปล)",
    "cjk_leak": "มีอักษรจีน/ญี่ปุ่น/เกาหลีหลุด",
    "raw_name": "ชื่อบุคคลไม่ถูกแปลงเป็นไทย",
    "em_dash": "มี em-dash (ผิดกติกา no-ai-slop)",
    "wire_caps": "หัวข่าวเป็นตัวพิมพ์ใหญ่แบบ wire ดิบ",
    "empty_body": "การ์ดไม่มีเนื้อ (body ว่าง)",
}


def _ascii_ratio(text: str) -> float:
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return 0.0
    return sum(1 for c in letters if c.isascii()) / len(letters)


def auto_qc(sent_rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Run every check over the week's sent rows. Returns
    {check: {"count": n, "examples": [headline, ...]}} for checks that hit."""
    hits: dict[str, dict[str, Any]] = {}

    def _hit(check: str, example: str) -> None:
        d = hits.setdefault(check, {"count": 0, "examples": []})
        d["count"] += 1
        if example and len(d["examples"]) < 2:
            d["examples"].append(example[:60])

    for r in sent_rows:
        head = str(r.get("headline_th") or "").strip()
        body = str(r.get("body_th") or "").strip()
        impact = str(r.get("impact_th") or "").strip()
        blob = " ".join((head, body, impact))
        if not blob.strip():
            continue

        # Thai chars are alphabetic too, so a mostly-ASCII headline of real
        # length means the rewrite shipped in English. Fallback cards are the
        # usual culprit; either way the reader got the wrong language.
        if head and len(head) > 12 and _ascii_ratio(head) > 0.8:
            _hit("untranslated", head)
        if _CJK_RE.search(blob):
            _hit("cjk_leak", head)
        for name in _GLOSSARY_NAMES:
            if re.search(rf"\b{re.escape(name)}\b", blob):
                _hit("raw_name", f"{name}: {head}")
                break
        if "—" in blob:
            _hit("em_dash", head)
        # Wire-format leftover: EXPEDIA GROUP Q2 EPS $4.14 style — mostly
        # uppercase ASCII survived into the "Thai" headline.
        ascii_letters = [c for c in head if c.isalpha() and c.isascii()]
        if (len(ascii_letters) > 10
                and sum(1 for c in ascii_letters if c.isupper()) / len(ascii_letters) > 0.7):
            _hit("wire_caps", head)
        if head and not body:
            _hit("empty_body", head)
    return hits


def analyze(content_rows: list[dict[str, Any]],
            sent_rows: list[dict[str, Any]],
            calib_rows: list[dict[str, Any]],
            *, now: datetime) -> dict[str, Any]:
    """Aggregate the last WEEK_DAYS days into the self-review summary."""
    cutoff = now - timedelta(days=WEEK_DAYS)

    # ---- delivery volume, straight from sent_log (still inside its 30d) ----
    by_route: Counter[str] = Counter()
    n_failed = 0
    for r in sent_rows:
        route = str(r.get("route_type") or "")
        if route not in ("breaking", "alert", "digest"):
            continue
        if str(r.get("event_id") or "").startswith("digest:"):
            continue                    # round marker, not a card
        ts = parse_iso(r.get("sent_ts"))
        if ts is None or ts < cutoff:
            continue
        if str(r.get("line_status") or "").strip() in _DELIVERED:
            by_route[route] += 1
        else:
            n_failed += 1

    # ---- content_log: what was said + what the operator annotated ----
    n_logged_sent = n_logged_rejected = 0
    n_fb_ok = n_fb_issue = 0
    issues_by_type: Counter[str] = Counter()
    reject_reasons: Counter[str] = Counter()
    missed: list[dict[str, Any]] = []
    fixes: list[dict[str, Any]] = []
    n_fallback = n_degraded = 0
    rejected_ids: list[str] = []
    sent_in_window: list[dict[str, Any]] = []

    for r in content_rows:
        ts = parse_ts_ict(r.get("ts_ict"))
        if ts is None or ts < cutoff:
            continue
        decision = str(r.get("decision") or "").strip()
        flags = str(r.get("flags") or "")
        fb_type = str(r.get("fb_type") or "").strip().lower()
        state = _fb_state(r)

        if decision == "sent":
            n_logged_sent += 1
            sent_in_window.append(r)
            if "fallback" in flags:
                n_fallback += 1
            if "degraded" in flags:
                n_degraded += 1
        elif decision == "rejected":
            n_logged_rejected += 1
            reject_reasons[_reject_reason(flags)] += 1
            if r.get("event_id"):
                rejected_ids.append(str(r["event_id"]))

        if state == "ok":
            n_fb_ok += 1
        elif state == "issue":
            n_fb_issue += 1
            issues_by_type[fb_type or "other"] += 1
            if fb_type == "missed" or (decision == "rejected" and state == "issue"):
                missed.append({
                    "en_title": str(r.get("en_title") or r.get("headline_th") or "")[:70],
                    "reason": _reject_reason(flags),
                })
        fix = str(r.get("fb_fix") or "").strip()
        if fix:
            fixes.append({
                "before": str(r.get("headline_th") or r.get("en_title") or "")[:60],
                "after": fix[:80],
                "type": fb_type or "other",
            })

    # ---- did the tape care about what we rejected? (join calibration_log) ----
    r30_by_id = {
        str(c.get("event_id") or ""): _to_float(c.get("xau_return_30m"))
        for c in calib_rows
    }
    high_move_rejects = []
    for eid in rejected_ids:
        r30 = r30_by_id.get(eid)
        if r30 is not None and abs(r30) >= HIGH_MOVE_PCT:
            high_move_rejects.append({"event_id": eid, "r30": r30})
    high_move_rejects.sort(key=lambda m: abs(m["r30"]), reverse=True)

    summary = {
        "by_route": dict(by_route),
        "n_cards": sum(by_route.values()),
        "n_failed": n_failed,
        "n_logged_sent": n_logged_sent,
        "n_logged_rejected": n_logged_rejected,
        "n_reviewed": n_fb_ok + n_fb_issue,
        "n_fb_ok": n_fb_ok,
        "n_fb_issue": n_fb_issue,
        "issues_by_type": dict(issues_by_type),
        "missed": missed[:5],
        "n_missed": len(missed),
        "fixes": fixes[:5],
        "n_fixes": len(fixes),
        "n_fallback": n_fallback,
        "n_degraded": n_degraded,
        "reject_reasons": dict(reject_reasons),
        "high_move_rejects": high_move_rejects[:3],
        # Deterministic self-inspection of the week's shipped copy — the loop
        # produces findings even when the operator gave zero manual feedback.
        "auto_qc": auto_qc(sent_in_window),
    }
    summary["suggestions"] = build_suggestions(summary)
    return summary


def build_suggestions(s: dict[str, Any]) -> list[str]:
    """Rule engine. Each suggestion cites its own evidence; order = severity.
    Empty list means 'nothing actionable this week' — the card says that."""
    out: list[str] = []
    issues = s.get("issues_by_type") or {}

    # 1. Operator flagged wrongly-rejected stories — the over-filter tripwire.
    if s.get("n_missed"):
        top = Counter(m["reason"] for m in s.get("missed") or []).most_common(1)
        why = f" (เหตุผลตัดที่เจอบ่อย: {top[0][0]})" if top else ""
        out.append(f"มี {s['n_missed']} ข่าวถูก mark ว่าไม่ควรตัด{why} "
                   "— ทบทวนเกณฑ์ reject ตัวนั้นก่อนตัวอื่น")

    # 2. The tape moved on stories we rejected — filter may be missing signal.
    hm = s.get("high_move_rejects") or []
    if len(hm) >= 2:
        out.append(f"ข่าวที่ถูกตัดแล้วทอง 30 นาทีขยับ ≥{HIGH_MOVE_PCT}% มี "
                   f"{len(hm)} ข่าว (แรงสุด {hm[0]['r30']:+.2f}%) "
                   "— ตรวจว่า relevance gate เข้มเกินไปกับหมวดนั้น")

    # 3. Repeated language problems → glossary additions are the cheap fix.
    n_lang = issues.get("translation", 0) + issues.get("typo", 0)
    if n_lang >= 2:
        ex = next((f for f in s.get("fixes") or []
                   if f["type"] in ("translation", "typo")), None)
        ex_txt = f' เช่น "{ex["after"]}"' if ex else ""
        out.append(f"คำแปล/คำผิดถูกติ {n_lang} ครั้ง — เพิ่ม glossary จาก fb_fix "
                   f"({s.get('n_fixes', 0)} รายการ){ex_txt}")

    # 4. Verdict quality — the impact_th line is a prompt problem, not a data one.
    if issues.get("impact", 0) >= 2:
        out.append(f"บรรทัด impact ถูกติ {issues['impact']} ครั้ง "
                   "— ทบทวน prompt ส่วนวิเคราะห์ผลต่อทอง")

    # 5. Rendering complaints.
    if issues.get("display", 0) >= 2:
        out.append(f"การแสดงผลถูกติ {issues['display']} ครั้ง — ตรวจ layout Flex")

    # 6. Classifier degradation — cards went out at reduced quality.
    n_deg = s.get("n_fallback", 0) + s.get("n_degraded", 0)
    if n_deg:
        out.append(f"มีการ์ดคุณภาพลดรูป (fallback/degraded) {n_deg} ใบ "
                   "— ตรวจ quota/สถานะ Claude+Gemini")

    # 7. Delivery failures.
    if s.get("n_failed"):
        out.append(f"LINE ส่งไม่สำเร็จ {s['n_failed']} ครั้งในสัปดาห์ "
                   "— ดู delivery_daily ว่ากระจุกวันไหน")

    # 8. Automatic QC findings — self-caught, no human feedback needed. Ranked
    # by count so the most frequent defect surfaces first when the cap bites.
    qc = s.get("auto_qc") or {}
    for check, d in sorted(qc.items(), key=lambda kv: -kv[1]["count"]):
        label = _QC_LABELS_TH.get(check, check)
        ex = f' เช่น "{d["examples"][0]}"' if d.get("examples") else ""
        out.append(f"QC อัตโนมัติ: {label} {d['count']} ใบ{ex}")

    # 9. No feedback at all → gentle nudge. Auto-QC softens this from
    # "the loop is blind" to "the loop only sees what rules can see" — human
    # judgement on tone / impact quality still needs the fb_* columns.
    if not s.get("n_reviewed") and (s.get("n_logged_sent") or s.get("n_logged_rejected")):
        out.append("ยังไม่มี feedback คนใน content_log สัปดาห์นี้ (QC อัตโนมัติ"
                   "ทำงานแทนบางส่วนแล้ว) — ติเรื่อง tone/impact เพิ่มได้ถ้ามีเวลา")

    return out[:MAX_SUGGESTIONS]
